/*
   Part 1, Q.2
   Create Bronze Schema
*/

CREATE SCHEMA BRONZE;

CREATE TABLE BRONZE.LISTINGS (
    LISTING_ID VARCHAR,
    SCRAPE_ID VARCHAR,
    SCRAPED_DATE VARCHAR,
    HOST_ID VARCHAR,
    HOST_NAME VARCHAR,
    HOST_SINCE VARCHAR,
    HOST_IS_SUPERHOST VARCHAR,
    HOST_NEIGHBOURHOOD VARCHAR,
    LISTING_NEIGHBOURHOOD VARCHAR,
    PROPERTY_TYPE VARCHAR,
    ROOM_TYPE VARCHAR,
    ACCOMMODATES VARCHAR,
    PRICE VARCHAR,
    HAS_AVAILABILITY VARCHAR(1),
    AVAILABILITY_30 VARCHAR,
    NUMBER_OF_REVIEWS VARCHAR,
    REVIEW_SCORES_RATING VARCHAR,
    REVIEW_SCORES_ACCURACY VARCHAR,
    REVIEW_SCORES_CLEANLINESS VARCHAR,
    REVIEW_SCORES_CHECKIN VARCHAR,
    REVIEW_SCORES_COMMUNICATION VARCHAR,
    REVIEW_SCORES_VALUE VARCHAR
);

CREATE TABLE BRONZE.CENSUS_G01 (
    LGA_CODE_2016 VARCHAR NOT NULL,
    Tot_P_M VARCHAR,
    Tot_P_F VARCHAR,
    Tot_P_P VARCHAR,
    Age_0_4_yr_M VARCHAR,
    Age_0_4_yr_F VARCHAR,
    Age_0_4_yr_P VARCHAR,
    Age_5_14_yr_M VARCHAR,
    Age_5_14_yr_F VARCHAR,
    Age_5_14_yr_P VARCHAR,
    Age_15_19_yr_M VARCHAR,
    Age_15_19_yr_F VARCHAR,
    Age_15_19_yr_P VARCHAR,
    Age_20_24_yr_M VARCHAR,
    Age_20_24_yr_F VARCHAR,
    Age_20_24_yr_P VARCHAR,
    Age_25_34_yr_M VARCHAR,
    Age_25_34_yr_F VARCHAR,
    Age_25_34_yr_P VARCHAR,
    Age_35_44_yr_M VARCHAR,
    Age_35_44_yr_F VARCHAR,
    Age_35_44_yr_P VARCHAR,
    Age_45_54_yr_M VARCHAR,
    Age_45_54_yr_F VARCHAR,
    Age_45_54_yr_P VARCHAR,
    Age_55_64_yr_M VARCHAR,
    Age_55_64_yr_F VARCHAR,
    Age_55_64_yr_P VARCHAR,
    Age_65_74_yr_M VARCHAR,
    Age_65_74_yr_F VARCHAR,
    Age_65_74_yr_P VARCHAR,
    Age_75_84_yr_M VARCHAR,
    Age_75_84_yr_F VARCHAR,
    Age_75_84_yr_P VARCHAR,
    Age_85ov_M VARCHAR,
    Age_85ov_F VARCHAR,
    Age_85ov_P VARCHAR,
    Counted_Census_Night_home_M VARCHAR,
    Counted_Census_Night_home_F VARCHAR,
    Counted_Census_Night_home_P VARCHAR,
    Count_Census_Nt_Ewhere_Aust_M VARCHAR,
    Count_Census_Nt_Ewhere_Aust_F VARCHAR,
    Count_Census_Nt_Ewhere_Aust_P VARCHAR,
    Indigenous_psns_Aboriginal_M VARCHAR,
    Indigenous_psns_Aboriginal_F VARCHAR,
    Indigenous_psns_Aboriginal_P VARCHAR,
    Indig_psns_Torres_Strait_Is_M VARCHAR,
    Indig_psns_Torres_Strait_Is_F VARCHAR,
    Indig_psns_Torres_Strait_Is_P VARCHAR,
    Indig_Bth_Abor_Torres_St_Is_M VARCHAR,
    Indig_Bth_Abor_Torres_St_Is_F VARCHAR,
    Indig_Bth_Abor_Torres_St_Is_P VARCHAR,
    Indigenous_P_Tot_M VARCHAR,
    Indigenous_P_Tot_F VARCHAR,
    Indigenous_P_Tot_P VARCHAR,
    Birthplace_Australia_M VARCHAR,
    Birthplace_Australia_F VARCHAR,
    Birthplace_Australia_P VARCHAR,
    Birthplace_Elsewhere_M VARCHAR,
    Birthplace_Elsewhere_F VARCHAR,
    Birthplace_Elsewhere_P VARCHAR,
    Lang_spoken_home_Eng_only_M VARCHAR,
    Lang_spoken_home_Eng_only_F VARCHAR,
    Lang_spoken_home_Eng_only_P VARCHAR,
    Lang_spoken_home_Oth_Lang_M VARCHAR,
    Lang_spoken_home_Oth_Lang_F VARCHAR,
    Lang_spoken_home_Oth_Lang_P VARCHAR,
    Australian_citizen_M VARCHAR,
    Australian_citizen_F VARCHAR,
    Australian_citizen_P VARCHAR,
    Age_psns_att_educ_inst_0_4_M VARCHAR,
    Age_psns_att_educ_inst_0_4_F VARCHAR,
    Age_psns_att_educ_inst_0_4_P VARCHAR,
    Age_psns_att_educ_inst_5_14_M VARCHAR,
    Age_psns_att_educ_inst_5_14_F VARCHAR,
    Age_psns_att_educ_inst_5_14_P VARCHAR,
    Age_psns_att_edu_inst_15_19_M VARCHAR,
    Age_psns_att_edu_inst_15_19_F VARCHAR,
    Age_psns_att_edu_inst_15_19_P VARCHAR,
    Age_psns_att_edu_inst_20_24_M VARCHAR,
    Age_psns_att_edu_inst_20_24_F VARCHAR,
    Age_psns_att_edu_inst_20_24_P VARCHAR,
    Age_psns_att_edu_inst_25_ov_M VARCHAR,
    Age_psns_att_edu_inst_25_ov_F VARCHAR,
    Age_psns_att_edu_inst_25_ov_P VARCHAR,
    High_yr_schl_comp_Yr_12_eq_M VARCHAR,
    High_yr_schl_comp_Yr_12_eq_F VARCHAR,
    High_yr_schl_comp_Yr_12_eq_P VARCHAR,
    High_yr_schl_comp_Yr_11_eq_M VARCHAR,
    High_yr_schl_comp_Yr_11_eq_F VARCHAR,
    High_yr_schl_comp_Yr_11_eq_P VARCHAR,
    High_yr_schl_comp_Yr_10_eq_M VARCHAR,
    High_yr_schl_comp_Yr_10_eq_F VARCHAR,
    High_yr_schl_comp_Yr_10_eq_P VARCHAR,
    High_yr_schl_comp_Yr_9_eq_M VARCHAR,
    High_yr_schl_comp_Yr_9_eq_F VARCHAR,
    High_yr_schl_comp_Yr_9_eq_P VARCHAR,
    High_yr_schl_comp_Yr_8_belw_M VARCHAR,
    High_yr_schl_comp_Yr_8_belw_F VARCHAR,
    High_yr_schl_comp_Yr_8_belw_P VARCHAR,
    High_yr_schl_comp_D_n_g_sch_M VARCHAR,
    High_yr_schl_comp_D_n_g_sch_F VARCHAR,
    High_yr_schl_comp_D_n_g_sch_P VARCHAR,
    Count_psns_occ_priv_dwgs_M VARCHAR,
    Count_psns_occ_priv_dwgs_F VARCHAR,
    Count_psns_occ_priv_dwgs_P VARCHAR,
    Count_Persons_other_dwgs_M VARCHAR,
    Count_Persons_other_dwgs_F VARCHAR,
    Count_Persons_other_dwgs_P VARCHAR,
    PRIMARY KEY (LGA_CODE_2016)
);


CREATE TABLE BRONZE.CENSUS_G02 (
    LGA_CODE_2016 VARCHAR NOT NULL,
    Median_age_persons VARCHAR,
    Median_mortgage_repay_monthly VARCHAR,
    Median_tot_prsnl_inc_weekly VARCHAR,
    Median_rent_weekly VARCHAR,
    Median_tot_fam_inc_weekly VARCHAR,
    Average_num_psns_per_bedroom VARCHAR,
    Median_tot_hhd_inc_weekly VARCHAR,
    Average_household_size VARCHAR, 
    PRIMARY KEY (LGA_CODE_2016)
);


CREATE TABLE BRONZE.NSW_LGA_CODE (
    LGA_CODE VARCHAR PRIMARY KEY,
    LGA_NAME VARCHAR
);

CREATE TABLE BRONZE.NSW_LGA_SUBURB (
    LGA_NAME VARCHAR, 
    SUBURB_NAME VARCHAR
);