{{
    config(
        unique_key='lga_code',
        alias='g_census_g01'
    )
}}

WITH source AS (
    SELECT * FROM {{ ref('b_census_g01') }}
),
cleaned_data AS (
  SELECT
    CAST(REPLACE(LGA_CODE_2016, 'LGA', '') AS INT) AS lga_code,
    CAST(Tot_P_M AS INT) AS total_persons_m,
    CAST(Tot_P_F AS INT) AS total_persons_f,
    CAST(Tot_P_P AS INT) AS total_persons_p,
    CAST(Age_0_4_yr_M AS INT) AS age_0_4_m,
    CAST(Age_0_4_yr_F AS INT) AS age_0_4_f,
    CAST(Age_0_4_yr_P AS INT) AS age_0_4_p,
    CAST(Age_5_14_yr_M AS INT) AS age_5_14_m,
    CAST(Age_5_14_yr_F AS INT) AS age_5_14_f,
    CAST(Age_5_14_yr_P AS INT) AS age_5_14_p,
    CAST(Age_15_19_yr_M AS INT) AS age_15_19_m,
    CAST(Age_15_19_yr_F AS INT) AS age_15_19_f,
    CAST(Age_15_19_yr_P AS INT) AS age_15_19_p,
    CAST(Age_20_24_yr_M AS INT) AS age_20_24_m,
    CAST(Age_20_24_yr_F AS INT) AS age_20_24_f,
    CAST(Age_20_24_yr_P AS INT) AS age_20_24_p,
    CAST(Age_25_34_yr_M AS INT) AS age_25_34_m,
    CAST(Age_25_34_yr_F AS INT) AS age_25_34_f,
    CAST(Age_25_34_yr_P AS INT) AS age_25_34_p,
    CAST(Age_35_44_yr_M AS INT) AS age_35_44_m,
    CAST(Age_35_44_yr_F AS INT) AS age_35_44_f,
    CAST(Age_35_44_yr_P AS INT) AS age_35_44_p,
    CAST(Age_45_54_yr_M AS INT) AS age_45_54_m,
    CAST(Age_45_54_yr_F AS INT) AS age_45_54_f,
    CAST(Age_45_54_yr_P AS INT) AS age_45_54_p,
    CAST(Age_55_64_yr_M AS INT) AS age_55_64_m,
    CAST(Age_55_64_yr_F AS INT) AS age_55_64_f,
    CAST(Age_55_64_yr_P AS INT) AS age_55_64_p,
    CAST(Age_65_74_yr_M AS INT) AS age_65_74_m,
    CAST(Age_65_74_yr_F AS INT) AS age_65_74_f,
    CAST(Age_65_74_yr_P AS INT) AS age_65_74_p,
    CAST(Age_75_84_yr_M AS INT) AS age_75_84_m,
    CAST(Age_75_84_yr_F AS INT) AS age_75_84_f,
    CAST(Age_75_84_yr_P AS INT) AS age_75_84_p,
    CAST(Age_85ov_M AS INT) AS age_85_plus_m,
    CAST(Age_85ov_F AS INT) AS age_85_plus_f,
    CAST(Age_85ov_P AS INT) AS age_85_plus_p,
    CAST(Counted_Census_Night_home_M AS INT) AS counted_census_night_home_m,
    CAST(Counted_Census_Night_home_F AS INT) AS counted_census_night_home_f,
    CAST(Counted_Census_Night_home_P AS INT) AS counted_census_night_home_p,
    CAST(Count_Census_Nt_Ewhere_Aust_M AS INT) AS count_census_elsewhere_aust_m,
    CAST(Count_Census_Nt_Ewhere_Aust_F AS INT) AS count_census_elsewhere_aust_f,
    CAST(Count_Census_Nt_Ewhere_Aust_P AS INT) AS count_census_elsewhere_aust_p,
    CAST(Indigenous_psns_Aboriginal_M AS INT) AS indigenous_persons_aboriginal_m,
    CAST(Indigenous_psns_Aboriginal_F AS INT) AS indigenous_persons_aboriginal_f,
    CAST(Indigenous_psns_Aboriginal_P AS INT) AS indigenous_persons_aboriginal_p,
    CAST(Indig_psns_Torres_Strait_Is_M AS INT) AS indig_persons_torres_strait_islander_m,
    CAST(Indig_psns_Torres_Strait_Is_F AS INT) AS indig_persons_torres_strait_islander_f,
    CAST(Indig_psns_Torres_Strait_Is_P AS INT) AS indig_persons_torres_strait_islander_p,
    CAST(Indig_Bth_Abor_Torres_St_Is_M AS INT) AS indig_both_aboriginal_torres_strait_islander_m,
    CAST(Indig_Bth_Abor_Torres_St_Is_F AS INT) AS indig_both_aboriginal_torres_strait_islander_f,
    CAST(Indig_Bth_Abor_Torres_St_Is_P AS INT) AS indig_both_aboriginal_torres_strait_islander_p,
    CAST(Indigenous_P_Tot_M AS INT) AS indigenous_total_m,
    CAST(Indigenous_P_Tot_F AS INT) AS indigenous_total_f,
    CAST(Indigenous_P_Tot_P AS INT) AS indigenous_total_p,
    CAST(Birthplace_Australia_M AS INT) AS birthplace_australia_m,
    CAST(Birthplace_Australia_F AS INT) AS birthplace_australia_f,
    CAST(Birthplace_Australia_P AS INT) AS birthplace_australia_p,
    CAST(Birthplace_Elsewhere_M AS INT) AS birthplace_elsewhere_m,
    CAST(Birthplace_Elsewhere_F AS INT) AS birthplace_elsewhere_f,
    CAST(Birthplace_Elsewhere_P AS INT) AS birthplace_elsewhere_p,
    CAST(Lang_spoken_home_Eng_only_M AS INT) AS lang_spoken_home_eng_only_m,
    CAST(Lang_spoken_home_Eng_only_F AS INT) AS lang_spoken_home_eng_only_f,
    CAST(Lang_spoken_home_Eng_only_P AS INT) AS lang_spoken_home_eng_only_p,
    CAST(Lang_spoken_home_Oth_Lang_M AS INT) AS lang_spoken_home_oth_lang_m,
    CAST(Lang_spoken_home_Oth_Lang_F AS INT) AS lang_spoken_home_oth_lang_f,
    CAST(Lang_spoken_home_Oth_Lang_P AS INT) AS lang_spoken_home_oth_lang_p,
    CAST(Australian_citizen_M AS INT) AS australian_citizen_m,
    CAST(Australian_citizen_F AS INT) AS australian_citizen_f,
    CAST(Australian_citizen_P AS INT) AS australian_citizen_p,
    CAST(Age_psns_att_educ_inst_0_4_M AS INT) AS age_psns_att_educ_inst_0_4_m,
    CAST(Age_psns_att_educ_inst_0_4_F AS INT) AS age_psns_att_educ_inst_0_4_f,
    CAST(Age_psns_att_educ_inst_0_4_P AS INT) AS age_psns_att_educ_inst_0_4_p,
    CAST(Age_psns_att_educ_inst_5_14_M AS INT) AS age_psns_att_educ_inst_5_14_m,
    CAST(Age_psns_att_educ_inst_5_14_F AS INT) AS age_psns_att_educ_inst_5_14_f,
    CAST(Age_psns_att_educ_inst_5_14_P AS INT) AS age_psns_att_educ_inst_5_14_p,
    CAST(Age_psns_att_edu_inst_15_19_M AS INT) AS age_psns_att_edu_inst_15_19_m,
    CAST(Age_psns_att_edu_inst_15_19_F AS INT) AS age_psns_att_edu_inst_15_19_f,
    CAST(Age_psns_att_edu_inst_15_19_P AS INT) AS age_psns_att_edu_inst_15_19_p,
    CAST(Age_psns_att_edu_inst_20_24_M AS INT) AS age_psns_att_edu_inst_20_24_m,
    CAST(Age_psns_att_edu_inst_20_24_F AS INT) AS age_psns_att_edu_inst_20_24_f,
    CAST(Age_psns_att_edu_inst_20_24_P AS INT) AS age_psns_att_edu_inst_20_24_p,
    CAST(Age_psns_att_edu_inst_25_ov_M AS INT) AS age_psns_att_edu_inst_25_ov_m,
    CAST(Age_psns_att_edu_inst_25_ov_F AS INT) AS age_psns_att_edu_inst_25_ov_f,
    CAST(Age_psns_att_edu_inst_25_ov_P AS INT) AS age_psns_att_edu_inst_25_ov_p
  FROM source
)
SELECT * FROM cleaned_data